version: "3.7"

services:

  node:
    build:
      args:
        user: mastermind
        uid: 1001
      context: ./.docker/node
    networks: [frontend, backend]
    volumes:
      [.:/app]
    ports:
      [1234:1234]
    container_name: node_mastermind
    tty: true

  apache:
    build:
      context: ./.docker/apache
    networks: [frontend, backend]
    ports:
      [8080:80]
    volumes:
      [.:/app]
    container_name: apache_mastermind
networks:
  frontend:
  backend:
